_956‍.x([["default",()=>_956‍.o]]);const asyncErrorHandler = controlFunction => (req,res,next) => {
    Promise.resolve(controlFunction(req,res,next)).catch(next)
}

_956‍.d(asyncErrorHandler);